#!/bin/bash

# Setup the touchpad for i3

# Get id of touchpad
id=`xinput list | grep "Touchpad" | cut -d'=' -f2 | cut -d'[' -f1`


# Natural scrolling
natural_scrolling_id=`xinput list-props $id | \
                      grep "Natural Scrolling Enabled (" \
                      | cut -d'(' -f2 | cut -d')' -f1`

# Set the property to true
xinput --set-prop $id $natural_scrolling_id 1

# Tap to click
tap_to_click_id=`xinput list-props $id | \
                      grep "Tapping Enabled (" \
                      | cut -d'(' -f2 | cut -d')' -f1`

# Set the property to true
xinput --set-prop $id $tap_to_click_id 1
